Repository Techwise-Team-15/my_pet, pull requests merged in 2023-08, with the labels that each got.

#122 Thought bubbles
  game_util/scene_items.py
  house_screen.py
  main_menu.py
  status_bars.py
Labels: Foundational

#134 Rock getting dirty and clean
  house_screen.py
Labels: Foundational

#135 commented overview and Adjusted time
  docs/index.md
  house_screen.py
Labels: bug, Discussion

#139 Added thought bubble to scene items
  game_config.py
  game_util/pet_config.py
  game_util/scene_items.py
  house_screen.py
Labels: enhancement

#142 Fixed rock pet collision
  game_util/scene_items.py
  game_util/sprite_sheet.py
  house_screen.py
  pets/pet_mudskipper.py
  pets/pet_raccoon.py
  pets/pet_rock.py
  src/table.py
Labels: bug, enhancement

#138 Eating branch
  house_screen.py
Labels: enhancement

#144 added the Raccoon background
  game_util/pet_config.py
  theme_items/raccoon_scene.png
Labels: enhancement

#148 Adding linkedin to website
  docs/index.md
Labels: documentation

#143 Raccoon screen
  game_util/pet_config.py
  game_util/scene_items.py
  house_screen.py
  main_menu.py
  pets/pet_raccoon.py
  raccoon_screen.py
  src/table.py
Labels: Foundational

#149 added score to the game - Donald Deal
  game_over.py
  game_util/scene_items.py
  house_screen.py
  raccoon_screen.py
Labels: enhancement

#152 Background music
  CombinedMenus.py
  assets/rock_sound_effects/fire_sound.mp3
  assets/rock_sound_effects/game_over.mp3
  assets/rock_sound_effects/misc_sound_effect.mp3
  assets/rock_sound_effects/watering_can.mp3
  game_util/__init__.py
  game_util/music_player.py
  game_util/pet_config.py
  house_screen.py
  main_menu.py
  raccoon_screen.py
Labels: enhancement

#153 Moved the rock location
  assets/rock_sound_effects/game_music.mp3
  assets/rock_sound_effects/pet_mad.mp3
  assets/rock_sound_effects/rock_in_bucket.mp3
  assets/rock_sound_effects/sleeping.mp3
  game_util/pet_config.py
  main_menu.py
  pet_selection.py
Labels: bug

#155 Sound btn
  game_config.py
  house_screen.py
  main_menu.py
  raccoon_screen.py
Labels: bug, enhancement

#157 Bug fix for sound on game_over.py
  game_config.py
  game_util/pet_config.py
  house_screen.py
  main_menu.py
  raccoon_screen.py
Labels: bug, enhancement

#158 Completed cup turns half full for raccoon and rock Donald Deal
  game_util/pet_config.py
  house_screen.py
  raccoon_screen.py
Labels: enhancement

#160 Sleeping pauses stat drain
  game_util/scene_items.py
  house_screen.py
  raccoon_screen.py
Labels: enhancement, Foundational

#156 Eating branch
  .gitignore
  load_name.py
  main_menu.py
  saved_names.txt
Labels: enhancement

#161 button fix Donald Deal
  main_menu.py
Labels: bug

#162 Gamecaption
  game_over.py
  game_util/pet_config.py
  game_util/scene_items.py
  game_util/sprite_sheet.py
  load_name.py
  main_menu.py
  pet_selection.py
  raccoon_screen.py
Labels: bug, enhancement

#163 Idle
  house_screen.py
  main_menu.py
  pets/pet_mudskipper.py
  pets/pet_raccoon.py
  pets/pet_rock.py
  raccoon_screen.py
Labels: bug, enhancement

#165 Load names
  .gitignore
  game_config.py
  game_over.py
  game_util/scene_items.py
  house_screen.py
  load_name.py
  main_menu.py
  saved_names.txt
Labels: bug

#150 added mudskipper main menu functionality
  game_util/pet_config.py
  game_util/scene_items.py
  main_menu.py
  mudskipper_screen.py
  mudskipper_screen_2.py
  pets/pet_mudskipper.py
Labels: enhancement

#169 Mudskipper cloud, bar and name fix
  game_util/scene_items.py
  mudskipper_screen_2.py
Labels: bug

#167 Vase
  game_util/pet_config.py
  game_util/scene_items.py
  house_screen.py
  main_menu.py
  mudskipper_screen_2.py
  pet_selection.py
  pets/pet_mudskipper.py
  raccoon_screen.py
  src/table.py
Labels: bug

#171 Added go home button
  game_over.py
  house_screen.py
  main_menu.py
  mudskipper_screen_2.py
  raccoon_screen.py
Labels: bug

#172 Mudskipper misbehaving
  game_util/pet_config.py
  mudskipper_screen_2.py
  pets/pet_raccoon.py
  src/table.py
Labels: enhancement

#173 Kill pet
  game_config.py
  game_over.py
  game_util/scene_items.py
  house_screen.py
  main_menu.py
  mudskipper_screen_2.py
  raccoon_screen.py
Labels: bug
