Repository Techwise-Team-15/my_pet, pull requests merged in 2023-07, with the labels that each got.

#44 Item animation added
  assets/__init__.py
  assets/table.py
  game_util/pet_config.py
  pet_selection.py
Labels: Foundational

#52 Added pet img for transparency fix
  game_util/pet_config.py
  pet_selection.py
  pets/pet_mudskipper.py
  pets/pet_raccoon.py
  pets/pet_rock.py
  sprites/mudskipper.png
  sprites/raccoon.png
  sprites/rock.png
Labels: bug

#51 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/code-adjustment.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#54 changed back screen size
  game_util/pet_config.py
Labels: bug

#65 Got the menus working together Don Deal 7/13/2023
  CombinedMenus.py
Labels: Foundational

#67 added imgs into assets
  assets/items.png
  assets/rock_img/porch_for_rock.png
  assets/rock_img/porch_set_up.png
  pet_selection.py
  src/__init__.py
  src/table.py
Labels: documentation

#83 Display Pet Information and Name
  game_util/pet_config.py
  main_menu.py
  pet_selection.py
  pets/pet_mudskipper.py
  pets/pet_raccoon.py
  pets/pet_rock.py
Labels: Foundational

#84 Pet info
  pet_selection.py
Labels: enhancement

#86 Game over and pet animation bug fix
  game_over.py
  game_util/pet_config.py
  house_screen.py
  main_menu.py
  pets/pet_mudskipper.py
  pets/pet_raccoon.py
  pets/pet_rock.py
Labels: bug, Foundational

#87 Deploying the docs on main branch
  docs/_config.yml
  docs/index.md
Labels: documentation

#88 Added rock selection Feature
  README.md
  house_screen.py
  main_menu.py
  pet_selection.py
Labels: Foundational

#92 Sleeping rock
  game_util/pet_config.py
  house_screen.py
  main_menu.py
Labels: enhancement, Foundational

#93 Play once
  house_screen.py
  main_menu.py
  pets/pet_mudskipper.py
  pets/pet_raccoon.py
  pets/pet_rock.py
Labels: bug, enhancement, Foundational

#96 Playing rock
  game_util/pet_config.py
  game_util/scene_items.py
  house_screen.py
Labels: Foundational

#97 Life recharges after playing
  game_util/scene_items.py
  house_screen.py
  main_menu.py
Labels: Foundational

#98 Playful
  game_util/scene_items.py
  house_screen.py
  main_menu.py
Labels: Foundational

#101 Rock drinks water and fills thirst
  game_util/pet_config.py
  game_util/scene_items.py
  house_screen.py
  pets/pet_rock.py
  sprites/rock_sprites.png
Labels: Foundational

#115 sound effects added
  assets/rock_sound_effects/FireSound.mp3
  assets/rock_sound_effects/MiscSoundeffect1.mp3
  assets/rock_sound_effects/Sleeping.mp3
  assets/rock_sound_effects/WateringCan (1).mp3
  assets/rock_sound_effects/braking_lamp.mp3
  assets/rock_sound_effects/rock_in_buckett.mp3
Labels: Foundational

#118 Added bar icons
  assets/heart.png
  game_util/__init__.py
  game_util/pet_config.py
  game_util/scene_items.py
  house_screen.py
Labels: enhancement

#124 updated README file with description.
  README.md
Labels: documentation

#130 Added another elif for quite button
  main_menu.py
Labels: bug

#131 Items reset back original Loc
  game_util/scene_items.py
  house_screen.py
Labels: bug
